# Generated by Django 4.1.7 on 2023-05-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
        ('paciente', '0002_eps_estado_paciente_eps_paciente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dream.dream'),
        ),
    ]
