# Generated by Django 4.1.7 on 2023-05-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padrino', '0001_initial'),
        ('paciente', '0003_paciente_dream'),
    ]

    operations = [
        migrations.CreateModel(
            name='padrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='paciente.paciente')),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='padrino.padrino')),
            ],
        ),
    ]
