# Generated by Django 4.1.7 on 2023-05-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_padrino'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
    ]
