# Generated by Django 4.1.7 on 2023-05-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dream',
            table='dream',
        ),
    ]
