# Generated by Django 4.1.7 on 2023-05-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familiar',
            table='familiar',
        ),
    ]
