# Generated by Django 4.1.7 on 2023-05-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0002_alter_familiar_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
